### ISSUE TITLE
hpatches_evaluation

### ISSUE THREAD

**Issue by zzkslam** [rpautrat/LISRD#7] opened 2021-01-11 08:38 UTC
Hello, When I am running your evaluation notebook in notebooks/hpatches_evaluation.ipynb, I get the error: No such file or directory: '/home/victor/LISRD/Documents/datasets/Hpatches_sequences/i_nijmegen/1.ppm.kornia_sift'. Where can I get these pictures?

**Comment by rpautrat** [comment] 2021-01-11 09:27
Hi,

These are not pictures, but the keypoint detection and description output given by the Kornia implementation of SIFT. We are here not providing the code to reproduce all the baselines outputs (like SIFT), because they come from different repos that are not maintained by us.

If you really want to reproduce the results for all baselines, you need to clone all the official repos of these methods and extract their keypoint features with their provided code. If you only care about evaluating LISRD, you can replace the 'models_name' field of the config in the notebooks by:
``` 'models_name': ['lisrd'],```
This will run the evaluation for LISRD only.

**Comment by zzkslam** [comment] 2021-01-11 10:00
Sorry to bother you again, this time it shows:FileNotFoundError: [Errno 2] No such file or directory: '/home/victor/LISRD/Documents/datasets/Hpatches_sequences/i_nijmegen/1.ppm.lisrd'. I Just downloaded _HPatches full sequences_ in [https://github.com/hpatches/hpatches-dataset](url) and put it in the folder, I guess I need to use demo_lisrd or your whole project to get the 1.ppm.lisrd. Can you give me some detailed instructions,thanks.

**Comment by rpautrat** [comment] 2021-01-11 11:14
Yes, you need to first export the keypoints detection and description of LISRD. You can use the `export_features.py` script, as explained in the ReadMe:
``` python -m lisrd.export_features <path to a txt file listing all your images> <name of the model (lisrd or lisrd_sift)> --checkpoint <path to checkpoint> --keypoints <type of keypoints (sift or superpoint)> --num_kp <number of keypoints (default: 2000)> ```

In your case, the txt file should be a list of the paths to all images of HPatches on your computer.

**Comment by zzkslam** [comment] 2021-01-11 13:13
Thank you very much,I have solved that problem with your help.Then I try to run _Viewpoint changes_ part, I meet this kind of problem
/home/victor/图片/2021-01-11 21-10-41屏幕截图.png

**Comment by zzkslam** [comment] 2021-01-11 13:14
Thank you very much,I have solved that problem with your help.Then I try to run _Viewpoint changes_ part, I meet this kind of problem：
![2021-01-11 21-10-41屏幕截图](https://user-images.githubusercontent.com/57522526/104186852-fe45bf00-5451-11eb-96e7-73d1fe149a58.png)

**Comment by rpautrat** [comment] 2021-01-11 14:29
It seems that the list mma[m] is empty in your case. My guess is that no HPatches images with viewpoint changes was found in the dataloader.

Are you using the [HPatches sequences](http://icvl.ee.ic.ac.uk/vbalnt/hpatches/hpatches-sequences-release.tar.gz) with the original data structure? The structure should be the following:
i_ajuntament -> 1.ppm, 2.ppm, 3.ppm,  ...
i_autannes
i_bologna
i_books
i_boutique
i_bridger
i_brooklyn
i_castle
i_chestnuts
i_contruction
i_crownday
i_crownnight
i_dc
i_dome
i_duda
i_fenis
i_fog
i_fruits
i_gonnenberg
i_greenhouse
i_greentea
i_indiana
i_kions
i_ktirio
i_kurhaus
i_leuven
i_lionday
i_lionnight
i_londonbridge
i_melon
i_miniature
i_nescafe
i_nijmegen
i_nuts
i_objects
i_parking
i_partyfood
i_pencils
i_pinard
i_pool
i_porta
i_resort
i_salon
i_santuario
i_school
i_ski
i_smurf
i_steps
i_table
i_tools
i_toy
i_troulos
i_veggies
i_village
i_whitebuilding
i_yellowtent
i_zion
v_abstract
v_adam
v_apprentices
v_artisans
v_astronautis
v_azzola
v_bark
v_bees
v_beyus
v_bip
v_bird
v_birdwoman
v_blueprint
v_boat
v_bricks
v_busstop
v_calder
v_cartooncity
v_charing
v_churchill
v_circus
v_coffeehouse
v_colors
v_courses
v_dirtywall
v_dogman
v_eastsouth
v_feast
v_fest
v_gardens
v_grace
v_graffiti
v_home
v_laptop
v_london
v_machines
v_man
v_maskedman
v_pomegranate
v_posters
v_samples
v_soldiers
v_strand
v_sunseason
v_tabletop
v_talent
v_tempera
v_there
v_underground
v_vitro
v_wall
v_wapping
v_war
v_weapons
v_woman
v_wormhole
v_wounded
v_yard
v_yuri

**Comment by zzkslam** [comment] 2021-01-11 15:39
OK,I got it.Thank you very much.

**Comment by zzkslam** [comment] 2021-01-12 08:37
Sorry to bother you again, when I run _hpatches_evaluation in notebook_, test result  of Illumination changes is similar to yours, but the test result  of Viewpoint changes is different:
![2021-01-12 16-35-05屏幕截图](https://user-images.githubusercontent.com/57522526/104289522-31d92580-54f4-11eb-8c1b-c3f456ec603f.png)
I use sift keypoints and the whole sequences of hpatches, thanks in advance, looking forward to your reply!

**Comment by rpautrat** [comment] 2021-01-12 08:50
I am glad to hear that you could reproduce the results on HPatches illumination.

The viewpoint experiment seems not to be working at all indeed. I suppose that there should be something wrong with the homographies, since it was working fine on the illumination split with no homographical change. Did you change anything related to homographies? Are you using the same image resolution when exporting the features with `export_features.py` and when launching the valuation on HPatches?

**Comment by zzkslam** [comment] 2021-01-12 11:46
I don't change anything with the homographies，I only used _export_features.py_ to cpoe with pictures in the same way like illumination and then used the code in _hpatches_evaluation_ in notebook(change the data_path and model_name):
![2021-01-12 19-31-43屏幕截图](https://user-images.githubusercontent.com/57522526/104310388-9903d380-550e-11eb-8dc2-b13ba9bf9e6f.png)

**Comment by rpautrat** [comment] 2021-01-12 14:02
What about the tqdm loading bar in your case? It seems to run only 10 iterations in your case, whereas it for me it runs through 285 and 295 iterations for the illumination and viewpoint respectively.

**Comment by zzkslam** [comment] 2021-01-12 14:20
Yes, I use two sequences for illumination and viewpoint respectively, so it only run 10 iterations. If I use the whole sequences, then the result is like this:
![2021-01-12 22-13-36屏幕截图](https://user-images.githubusercontent.com/57522526/104325565-bbecb280-5523-11eb-9ea6-6882b7185679.png)
My command to use _export_features.py_ is: _python -m lisrd.export_features /home/victor/LISRD/123456.txt lisrd --checkpoint /home/victor/LISRD/weights/lisrd_aachen.pth --keypoints sift --num_kp 2000_
123456.txt is like this:
![2021-01-12 22-19-26屏幕截图](https://user-images.githubusercontent.com/57522526/104326072-40d7cc00-5524-11eb-96dd-bc82e24d40e2.png)

**Comment by rpautrat** [comment] 2021-01-12 15:01
Ok I see. I re-ran the notebook with the current master version on my side and I get the same results as before. So there must be some difference with your setup.

You can try to inspect the exported files .lisrd for the viewpoint images and plot the detected keypoints, to check if everything is fine there. But I would expect so, if it works for the illumination part. The problem lies more probably in the homography processing. But I am not sure what is happening in your case... I think it would need some debugging in the execution of the `descriptor_evaluation.py` file, to check first the quality of the matching, and if it looks fine, what's wrong with the homographies.

**Comment by yakult98** [comment] 2021-03-24 13:53
Hello,I ran into the same problem as the author zzkslam when running the evaluation notebook in   notebooks/hpatches_evaluation.ipynb.
I want to know if I need to change the 'resize=Falese' into 'True' before I run the  
`python -m lisrd.export_features <path to a txt file listing all your images> <name of the model (lisrd or lisrd_sift)> --checkpoint <path to checkpoint> --keypoints <type of keypoints (sift or superpoint)> --num_kp <number of keypoints (default: 2000)>` ?

![微信图片_20210324214320](https://user-images.githubusercontent.com/68220187/112321738-46534e80-8ceb-11eb-9069-73bde8e9eebc.png)
![捕获1](https://user-images.githubusercontent.com/68220187/112319716-4baf9980-8ce9-11eb-8f74-c6e43f33179d.PNG)

Thanks!

**Comment by yakult98** [comment] 2021-03-26 02:03
I followed the instructions and got the correct results finally. Thanks a lot!

**Comment by rpautrat** [comment] 2021-03-26 08:19
Great to hear that! I guess it was the same problem for zzkslam, so I am closing this now.

**Closed by rpautrat** 2021-03-26 08:19 UTC
